bioinformatics: Install perl
gdbm is reinstalled because perl depends on gdbm --with-libgdbm-compat

Work around the Docker error:
==> Installing dependencies for homebrew/science/links-scaffolder: gdbm, berkeley-db, perl
Error: Invalid cross-device link - (/home/linuxbrew/.linuxbrew/Cellar/gdbm/1.13, /home/linuxbrew/.linuxbrew/Cellar/gdbm/1.13.tmp)